### ISSUE TITLE
Vector Drawables crash the app on Pre-Lollipop devices

### ISSUE THREAD

**Issue by shehabix** [jd-alexander/LikeButton#19]
This PR: https://github.com/jd-alexander/LikeButton/pull/17 is not fully handling the Vector drawables properly.
Steps to reproduce:
1-Run the demo app on an device or emulator with android < Lollipop
2-See the crash

```
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
```

**Comment by shehabix** [comment]
```
              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.like.example/com.like.example.MainActivity}: android.view.InflateException: Binary XML file line #57: Error inflating class <unknown>
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                   Caused by: android.view.InflateException: Binary XML file line #57: Error inflating class <unknown>
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                                      at com.like.example.MainActivity.onCreate(MainActivity.java:35)
                                                                      at android.app.Activity.performCreate(Activity.java:5133)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                      at com.like.example.MainActivity.onCreate(MainActivity.java:35) 
                                                                      at android.app.Activity.performCreate(Activity.java:5133) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_android_green_500_24dp.xml from drawable resource ID #0x7f02004f
                                                                      at android.content.res.Resources.loadDrawable(Resources.java:2091)
                                                                      at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
                                                                      at com.like.LikeButton.init(LikeButton.java:90)
                                                                      at com.like.LikeButton.<init>(LikeButton.java:66)
                                                                      at com.like.LikeButton.<init>(LikeButton.java:0)
                                                                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                      at com.like.example.MainActivity.onCreate(MainActivity.java:35) 
                                                                      at android.app.Activity.performCreate(Activity.java:5133) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
                                                                      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:897)
                                                                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:837)
                                                                      at android.content.res.Resources.loadDrawable(Resources.java:2087)
                                                                      at android.content.res.TypedArray.getDrawable(TypedArray.java:601) 
                                                                      at com.like.LikeButton.init(LikeButton.java:90) 
                                                                      at com.like.LikeButton.<init>(LikeButton.java:66) 
                                                                      at com.like.LikeButton.<init>(LikeButton.java:0) 
                                                                      at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                      at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                      at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839) 
                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:745) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                      at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                      at com.like.example.MainActivity.onCreate(MainActivity.java:35) 
                                                                      at android.app.Activity.performCreate(Activity.java:5133) 
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175) 
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261) 
                                                                      at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by shehabix** [comment]
I will create a Pull Request shortly, the fix is actually straight forward.

**Comment by shehabix** [comment]
Here is the fix:
https://github.com/jd-alexander/LikeButton/pull/20

**Comment by jd-alexander** [comment]
Okay, will check it out and merge.
